export const MENU_UNIFICADO = [
  {
    id: 1,
    label: 'MENU',
    isTitle: true,
  },
  {
    id: 2,
    label: 'Home',
    icon: 'ri-home-4-line',
    link: '/',
  },
  {
    id: 3,
    label: 'Dashboards',
    icon: 'ri-dashboard-2-line',
    isCollapsed: true,
    subItems: [
      {
        id: 31,
        label: 'Painel',
        link: '/dashboard',
        parentId: 3,
      },
      {
        id: 32,
        label: 'Analytics',
        link: '/analytics',
        parentId: 3,
      },
      {
        id: 33,
        label: 'Projetos',
        link: '/projects',
        parentId: 3,
      },
      {
        id: 34,
        label: 'NFT',
        link: '/nft',
        parentId: 3,
      },
      {
        id: 35,
        label: 'Vagas',
        link: '/job',
        parentId: 3,
      },
      {
        id: 36,
        label: 'Blog',
        link: '/dashboard-blog',
        parentId: 3,
      },
    ],
  },

  {
    id: 10,
    label: 'APLICAÇÕES',
    isTitle: true,
  },
  {
    id: 12,
    label: 'Projetos',
    icon: 'ri-folder-3-line',
    isCollapsed: true,
    subItems: [
      { id: 121, label: 'Lista', link: '/projects/list', parentId: 12 },
      { id: 122, label: 'Visão geral', link: '/projects/overview', parentId: 12 },
      { id: 123, label: 'Criar', link: '/projects/create', parentId: 12 },
    ],
  },
  {
    id: 17,
    label: 'Tickets',
    icon: 'ri-customer-service-2-line',
    isCollapsed: true,
    subItems: [
      { id: 171, label: 'Geral', link: '/tickets/list', parentId: 17 },
    ],
  },

  {
    id: 1000,
    label: 'Cadastro',
    icon: 'ri-file-list-3-line',
    isCollapsed: true,
    subItems: [
      {
        id: 1001,
        label: 'Cliente',
        link: '/cadastro/clientes',
        parentId: 1000,
      },
      {
        id: 1002,
        label: 'Operador',
        link: '/cadastro/operadores',
        parentId: 1000,
      },
      {
        id: 1003,
        label: 'Funcionário',
        link: '/cadastro/funcionarios',
        parentId: 1000,
      },
      {
        id: 1004,
        label: 'Indicação',
        link: '/cadastro/indicacoes',
        parentId: 1000,
      },
      {
        id: 1005,
        label: 'Cliente Grupo',
        link: '/cadastro/cliente-grupos',
        parentId: 1000,
      },
    ],
  },
  {
    id: 1100,
    label: 'Configuração',
    icon: 'ri-settings-3-line',
    link: '/configuracao',
  },

  {
    id: 2000,
    label: 'PÁGINAS',
    isTitle: true,
  },
  {
    id: 2001,
    label: 'Páginas',
    icon: 'ri-pages-line',
    isCollapsed: true,
    subItems: [
      { id: 2002, label: 'Starter', link: '/pages/starter', parentId: 2001 },
      { id: 2003, label: 'Perfil', link: '/pages/profile', parentId: 2001 },
      { id: 2004, label: 'Configurar perfil', link: '/pages/profile-setting', parentId: 2001 },
      { id: 2005, label: 'Equipe', link: '/pages/team', parentId: 2001 },
      { id: 2006, label: 'Timeline', link: '/pages/timeline', parentId: 2001 },
      { id: 2007, label: 'FAQ', link: '/pages/faqs', parentId: 2001 },
      { id: 2008, label: 'Preços', link: '/pages/pricing', parentId: 2001 },
      { id: 2009, label: 'Galeria', link: '/pages/gallery', parentId: 2001 },
      { id: 2010, label: 'Mapa do site', link: '/pages/sitemap', parentId: 2001 },
      { id: 2011, label: 'Busca', link: '/pages/search-results', parentId: 2001 },
      { id: 2012, label: 'Política de privacidade', link: '/pages/privacy-policy', parentId: 2001 },
      { id: 2013, label: 'Termos', link: '/pages/terms-condition', parentId: 2001 },
      { id: 2014, label: 'Blog - Lista', link: '/pages/pages-blog-list', parentId: 2001 },
      { id: 2015, label: 'Blog - Grid', link: '/pages/pages-blog-grid', parentId: 2001 },
      { id: 2016, label: 'Blog - Overview', link: '/pages/pages-blog-overview', parentId: 2001 },
    ],
  },

  {
    id: 3000,
    label: 'COMPONENTES',
    isTitle: true,
  },
  {
    id: 3001,
    label: 'Base UI',
    icon: 'ri-pencil-ruler-2-line',
    isCollapsed: true,
    subItems: [
      { id: 3002, label: 'Alertas', link: '/ui/alerts', parentId: 3001 },
      { id: 3003, label: 'Badges', link: '/ui/badges', parentId: 3001 },
      { id: 3004, label: 'Botões', link: '/ui/buttons', parentId: 3001 },
      { id: 3005, label: 'Cards', link: '/ui/cards', parentId: 3001 },
      { id: 3006, label: 'Carousel', link: '/ui/carousel', parentId: 3001 },
      { id: 3007, label: 'Dropdowns', link: '/ui/dropdowns', parentId: 3001 },
      { id: 3008, label: 'Grid', link: '/ui/grid', parentId: 3001 },
      { id: 3009, label: 'Imagens', link: '/ui/images', parentId: 3001 },
      { id: 3010, label: 'Tabs', link: '/ui/tabs', parentId: 3001 },
      { id: 3011, label: 'Cores', link: '/ui/colors', parentId: 3001 },
      { id: 3012, label: 'Accordions', link: '/ui/accordions', parentId: 3001 },
      { id: 3013, label: 'Modals', link: '/ui/modals', parentId: 3001 },
      { id: 3014, label: 'Placeholder', link: '/ui/placeholder', parentId: 3001 },
      { id: 3015, label: 'Progresso', link: '/ui/progress', parentId: 3001 },
      { id: 3016, label: 'Notificações', link: '/ui/notifications', parentId: 3001 },
      { id: 3017, label: 'Media', link: '/ui/media', parentId: 3001 },
      { id: 3018, label: 'Vídeo', link: '/ui/video', parentId: 3001 },
      { id: 3019, label: 'Tipografia', link: '/ui/typography', parentId: 3001 },
      { id: 3020, label: 'Listas', link: '/ui/list', parentId: 3001 },
      { id: 3021, label: 'Geral', link: '/ui/general', parentId: 3001 },
      { id: 3022, label: 'Ribbons', link: '/ui/ribbons', parentId: 3001 },
      { id: 3023, label: 'Utilitários', link: '/ui/utilities', parentId: 3001 },
      { id: 3024, label: 'Links', link: '/ui/links', parentId: 3001 },
    ],
  },
  {
    id: 3100,
    label: 'UI Avançado',
    icon: 'ri-stack-line',
    isCollapsed: true,
    subItems: [
      { id: 3101, label: 'SweetAlert', link: '/advance-ui/sweetalerts', parentId: 3100 },
      { id: 3102, label: 'Scrollbar', link: '/advance-ui/scrollbar', parentId: 3100 },
      { id: 3103, label: 'Tour', link: '/advance-ui/tour', parentId: 3100 },
      { id: 3104, label: 'Swiper', link: '/advance-ui/swiper', parentId: 3100 },
      { id: 3105, label: 'Ratings', link: '/advance-ui/ratings', parentId: 3100 },
      { id: 3106, label: 'Highlight', link: '/advance-ui/highlight', parentId: 3100 },
      { id: 3107, label: 'Scrollspy', link: '/advance-ui/scrollspy', parentId: 3100 },
    ],
  },
  {
    id: 3200,
    label: 'Formulários',
    icon: 'ri-file-edit-line',
    isCollapsed: true,
    subItems: [
      { id: 3201, label: 'Básico', link: '/forms/basic', parentId: 3200 },
      { id: 3202, label: 'Select', link: '/forms/select', parentId: 3200 },
      { id: 3203, label: 'Checkbox / Radios', link: '/forms/checkboxs-radios', parentId: 3200 },
      { id: 3204, label: 'Pickers', link: '/forms/pickers', parentId: 3200 },
      { id: 3205, label: 'Máscaras', link: '/forms/masks', parentId: 3200 },
      { id: 3206, label: 'Avançado', link: '/forms/advanced', parentId: 3200 },
      { id: 3207, label: 'Range sliders', link: '/forms/range-sliders', parentId: 3200 },
      { id: 3208, label: 'Validação', link: '/forms/validation', parentId: 3200 },
      { id: 3209, label: 'Wizard', link: '/forms/wizard', parentId: 3200 },
      { id: 3210, label: 'Editors', link: '/forms/editors', parentId: 3200 },
      { id: 3211, label: 'Upload de arquivos', link: '/forms/file-uploads', parentId: 3200 },
      { id: 3212, label: 'Layouts', link: '/forms/layouts', parentId: 3200 },
    ],
  },
  {
    id: 3400,
    label: 'Gráficos',
    icon: 'ri-pie-chart-line',
    isCollapsed: true,
    subItems: [
      { id: 3401, label: 'Apex Line', link: '/charts/apex-line', parentId: 3400 },
      { id: 3402, label: 'Apex Area', link: '/charts/apex-area', parentId: 3400 },
      { id: 3403, label: 'Apex Column', link: '/charts/apex-column', parentId: 3400 },
      { id: 3404, label: 'Apex Bar', link: '/charts/apex-bar', parentId: 3400 },
      { id: 3405, label: 'Apex Mixed', link: '/charts/apex-mixed', parentId: 3400 },
      { id: 3406, label: 'Apex Timeline', link: '/charts/apex-timeline', parentId: 3400 },
      { id: 3407, label: 'Apex Candlestick', link: '/charts/apex-candlestick', parentId: 3400 },
      { id: 3408, label: 'Apex Boxplot', link: '/charts/apex-boxplot', parentId: 3400 },
      { id: 3409, label: 'Apex Bubble', link: '/charts/apex-bubble', parentId: 3400 },
      { id: 3410, label: 'Apex Scatter', link: '/charts/apex-scatter', parentId: 3400 },
      { id: 3411, label: 'Apex Heatmap', link: '/charts/apex-heatmap', parentId: 3400 },
      { id: 3412, label: 'Apex Treemap', link: '/charts/apex-treemap', parentId: 3400 },
      { id: 3413, label: 'Apex Pie', link: '/charts/apex-pie', parentId: 3400 },
      { id: 3414, label: 'Apex Radialbar', link: '/charts/apex-radialbar', parentId: 3400 },
      { id: 3415, label: 'Apex Radar', link: '/charts/apex-radar', parentId: 3400 },
      { id: 3416, label: 'Apex Polar', link: '/charts/apex-polar', parentId: 3400 },
      { id: 3417, label: 'ChartJS', link: '/charts/chartjs', parentId: 3400 },
      { id: 3418, label: 'ECharts', link: '/charts/echarts', parentId: 3400 },
      { id: 3419, label: 'Range Area', link: '/charts/range-area', parentId: 3400 },
      { id: 3420, label: 'Funnel', link: '/charts/funnel', parentId: 3400 },
      { id: 3421, label: 'Slope', link: '/charts/slope', parentId: 3400 },
    ],
  },
  {
    id: 3500,
    label: 'Ícones',
    icon: 'ri-emotion-happy-line',
    isCollapsed: true,
    subItems: [
      { id: 3501, label: 'Remix', link: '/icons/remix', parentId: 3500 },
      { id: 3502, label: 'Boxicons', link: '/icons/boxicons', parentId: 3500 },
      { id: 3503, label: 'Material Design', link: '/icons/materialdesign', parentId: 3500 },
      { id: 3504, label: 'Feather', link: '/icons/feather', parentId: 3500 },
      { id: 3505, label: 'Line Awesome', link: '/icons/lineawesome', parentId: 3500 },
      { id: 3506, label: 'Cripto', link: '/icons/icons-crypto', parentId: 3500 },
    ],
  },
];
